### ISSUE TITLE
Bin Packing and spreading scheduling

### ISSUE THREAD

**Issue by jxdn** [kai-scheduler/KAI-Scheduler#109]
Bin Packing & Spread Scheduling: Optimize node usage either by minimizing fragmentation (bin-packing) or increasing resiliency and load balancing (spread scheduling).

![Image](https://github.com/user-attachments/assets/6b3dfe16-d8be-4dca-99c8-26fe2dadf576)

the values.yaml 

![Image](https://github.com/user-attachments/assets/b3d31bf7-3712-41fd-93f9-cde3753d6b0c)

then I trie to deploy 7 pod with 1 GPU each, but still spreading.. .

i want to use bin packing.. where should I check ?

**Comment by romanbaron** [comment]
Hi @jxdn 👋 

The configuration above applied in a configmap that is read by the scheduler, check the value there first:
```
kubectl get cm -n kai-scheduler scheduler-config -o yaml
```

The expected state is that under nodeplacement plugin you will see the desired strategy:
```
name: nodeplacement
arguments:
  cpu: binpack
  gpu: binpack
```

If it is already the case, please provide more details from your cluster, like how many nodes you have and how many GPU device on each node? Are there other pods requesting GPU device already running on these nodes? Is it possible that your pods request other resources or have any scheduling constraints that prevent the pods to being scheduled as expected?

**Comment by jxdn** [comment]
Below my configmap @romanbaron 


```root@hgx-60:~# kubectl get cm -n kai-scheduler scheduler-config -o yaml
apiVersion: v1
data:
  config.yaml: |
    actions: allocate, consolidation, reclaim, preempt, stalegangeviction
    tiers:
      - plugins:
          - name: predicates
          - name: proportion
          - name: priority
          - name: nodeavailability
          - name: resourcetype
          - name: podaffinity
          - name: elastic
          - name: kubeflow
          - name: ray
          - name: taskorder
          - name: nominatednode
          - name: dynamicresources
          - name: gpupack
          - name: gpusharingorder
          - name: nodeplacement
            arguments:
              cpu: binpack
              gpu: binpack
```

my cluster only have 2 nodes

```
NAME     STATUS   ROLES           AGE   VERSION
hgx-58   Ready    <none>          65d   v1.29.14
hgx-60   Ready    control-plane   67d   v1.30.10
```

my deployment are

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gpu-deployment
  labels:
    app: nginx-gpu
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx-gpu
  template:
    metadata:
      labels:
        app: nginx-gpu
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
            memory: "512Mi"
            cpu: "500m"
```



each with 8 GPU per node, I deploy and its look like this. 



```nginx-gpu-deployment-779cf78d8d-745tp   1/1     Running     0          18s     10.244.249.167   hgx-58   <none>           <none>
nginx-gpu-deployment-779cf78d8d-7654z   1/1     Running     0          18s     10.244.249.174   hgx-58   <none>           <none>
nginx-gpu-deployment-779cf78d8d-mk62n   1/1     Running     0          18s     10.244.249.133   hgx-58   <none>           <none>
nginx-gpu-deployment-779cf78d8d-t72dw   1/1     Running     0          18s     10.244.214.81    hgx-60   <none>           <none>
nginx-gpu-deployment-779cf78d8d-wnbdk   1/1     Running     0          18s     10.244.249.168   hgx-58   <none>           <none>
nginx-gpu-deployment-779cf78d8d-z54rq   1/1     Running     0          18s     10.244.214.101   hgx-60   <none>           <none>
nginx-gpu-deployment-779cf78d8d-zx9f4   1/1     Running     0          18s     10.244.214.82    hgx-60   <none>           <none>```
