### ISSUE TITLE
Enable node-pool quota scoping in KAI Scheduler Queue

### ISSUE THREAD

**Issue by larryyu1285** [kai-scheduler/KAI-Scheduler#133]
### What you would like to be added?

Add support for scoping a Queue’s resource quotas to a subset of nodes via a `nodeSelector` or `nodeAffinity` field on the Queue CRD. For example:

```yaml
apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
  name: default
spec:
  nodeSelector:
    nodepool: node-1, node-2 # ONLY select resources from node-1 or node-2. Other nodes are ignored even if they have enough resources.
  resources:
    cpu:
      quota: 2000m
      limit: 4000m
      overQuotaWeight: 1
    gpu:
      quota: 2
      limit: 4
      overQuotaWeight: 1
    memory:
      quota: 16Gi
      limit: 32Gi
      overQuotaWeight: 1
```

### Why is this needed?

Currently, Queue quotas in KAI are enforced cluster-wide, and users must apply pod-level nodeSelectors or affinity rules manually to corral workloads onto specific pools.

Without native node-scoped quotas, administrators resort to brittle workarounds—duplicating queues, adding affinities everywhere.
