### ISSUE TITLE
recommended way to enforce cluster-wide quota resource limits on pod creation

### ISSUE THREAD

**Issue by sam-huang1223** [kai-scheduler/KAI-Scheduler#140]
### What you would like to be added?

a way to force newly created workloads to use the KAI scheduler and be tracked under the KAI quota system

### Why is this needed?

currently as i understand it a bad player could simply elect to use the default scheduler (leave out KAI scheduler name from their pod template) to bypass / exceed their queue limit, i want to understand how to prevent this type of behaviour

**Comment by davidLif** [comment]
Hello @sam-huang1223,

The KAI scheduler is not intended to replace the default-scheduler. For example, It is recommened that the k8s system pods (usually found under the kube-system namespace) will be scheduled by the default scheduler. The logic for determining which pods KAI should schedule can vary across systems.

With that said, one possible way of preventing users from submitting "non KAI scheduled jobs" can be achived like this:
1- Restrict the users RBAC in the cluster so they can submit jobs/pods only to a given set of namespaces.
2- Add an admission webhook that will insure that all jobs submitted to this set of namespaces are submitted with KAI set as the scheduler. 
As an example, you can look at [this](https://github.com/ArmedGuy/k8s-nvidia-runtime-admission-controller) admission controller and re-purposed the code for the schedulerName field instead of runtimeClassName.

**Comment by sam-huang1223** [comment]
got it i don't want to muck around with go but i think i can do admission controller behaviour via kyverno so i'll try and post my solution here if i can get something working - thanks for the quick response!

**Comment by sam-huang1223** [comment]
cool this works well it seems like

```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-pod-schedulername-kai-scheduler
  namespace: default
  annotations:
    policies.kyverno.io/title: Require Pod schedulerName to be kai-scheduler
    policies.kyverno.io/category: Multi-Tenancy, EKS Best Practices
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Must schedule in a queue with kai-scheduler
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-schedulername-kai-scheduler
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Pods must define the schedulerName field to be kai-scheduler."
      pattern:
        spec:
          schedulerName: "kai-scheduler"
```
